# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EV4eFRfsl6ekocZ_4xeTWXSbn0KYqm4X
"""

import random

# Generate a random number between 1 and 100
secret_number = random.randint(1, 100)

attempts = 0

print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 100.")

while True:
    guess = int(input("Enter your guess: "))
    attempts += 1

    if guess < secret_number:
        print("Too low! Try again.\n")

    elif guess > secret_number:
        print("Too high! Try again.\n")

    else:
        print(f"🎉 Congratulations! You guessed the number in {attempts} attempts.")
        break